import React, { Component } from "react";
import Plot from "react-plotly.js";

const graphData = {
  masterGraph: {
    title: "Stromal",
    model: "",
    xAxis: "X-Axis",
    yAxis: "Y-Axis",
    zAxis: "Z-Axis",
  },
};

class MySankeyStromalComponent extends Component {
  render() {
    return (
      <Plot
        data={[
          {
            type: "sankey",
            orientation: "h",
            node: {
              color: [
                "#e7ba52",
                "#6baed6",
                "#843c39",
                "#e7969c",
                "#3182bd",
                "#9c9ede",
                "#969696",
                "#31a354",
                "#fd8d3c",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
                "#d41020",
              ],
              label: [
                "Muscle",
                "Small_Intestine",
                "Vasculature",
                "Bladder",
                "Lung",
                "Thymus",
                "Trachea",
                "Large_Intestine",
                "Pancreas",
                "adventitial cell",
                "myofibroblast cell",
                "smooth muscle cell",
                "pericyte cell",
                "fast muscle cell",
                "bronchial smooth muscle cell",
                "vascular associated smooth muscle cell",
                "alveolar fibroblast",
                "slow muscle cell",
                "connective tissue cell",
                "fibroblast",
                "tendon cell",
                "pancreatic stellate cell",
                "mesenchymal stem cell",
                "skeletal muscle satellite stem cell",
              ],
              line: {
                color: "black",
                width: 0.5,
              },
              pad: 15,
              thickness: 20,
            },
            link: {
              source: [
                3,
                3,
                3,
                3,
                7,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                0,
                0,
                0,
                0,
                0,
                0,
                8,
                1,
                5,
                5,
                5,
                6,
                2,
                2,
                2,
              ],
              target: [
                19,
                10,
                12,
                11,
                19,
                9,
                16,
                14,
                19,
                10,
                12,
                15,
                13,
                22,
                12,
                23,
                17,
                20,
                21,
                19,
                13,
                19,
                15,
                18,
                19,
                12,
                11,
              ],
              value: [
                4932,
                2020,
                711,
                227,
                101,
                350,
                330,
                83,
                13,
                10,
                215,
                81,
                168,
                8565,
                1322,
                2896,
                91,
                181,
                39,
                25,
                86,
                673,
                691,
                249,
                3030,
                384,
                1268,
              ],
            },
          },
        ]}
        layout={{
          width: 800,
          height: 800,
          margin: {
            l: 50,
            r: 50,
            b: 80,
            t: 90,
            pad: 4,
          },
          title: graphData.masterGraph.title,
          annotations: [
            {
              text: graphData.masterGraph.model,
              font: {
                size: 14,
                color: "#444444",
              },
              showarrow: false,
              align: "center",
              x: 0.5,
              y: 1.1,
              xref: "paper",
              yref: "paper",
            },
          ],
          scene: {
            xaxis: {
              title: graphData.masterGraph.xAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            yaxis: {
              title: graphData.masterGraph.yAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            zaxis: {
              title: graphData.masterGraph.zAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
          },
        }}
      />
    );
  }
}

export default MySankeyStromalComponent;
