import React, { Component } from "react";
import Plot from "react-plotly.js";

const graphData = {
  masterGraph: {
    title: "Immune",
    model: "",
    xAxis: "X-Axis",
    yAxis: "Y-Axis",
    zAxis: "Z-Axis",
  },
};

class MySankeyImmuneComponent extends Component {
  render() {
    return (
      <Plot
        data={[
          {
            type: "sankey",
            orientation: "h",
            node: {
              color: [
                "#e7ba52",
                "#6baed6",
                "#843c39",
                "#e7969c",
                "#3182bd",
                "#7b4173",
                "#9c9ede",
                "#969696",
                "#31a354",
                "#d6616b",
                "#cedb9c",
                "#393b79",
                "#8c6d31",
                "#fd8d3c",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
                "#fc5b2e",
              ],
              label: [
                "Muscle",
                "Small_Intestine",
                "Vasculature",
                "Bladder",
                "Lung",
                "Kidney",
                "Thymus",
                "Trachea",
                "Large_Intestine",
                "Blood",
                "Bone_Marrow",
                "Spleen",
                "Lymph_Node",
                "Pancreas",
                "conventional dendritic cell type ii",
                "plasma cell",
                "cd4-positive, alpha-beta memory t cell",
                "naive b cell",
                "monocyte",
                "natural killer cell",
                "hematopoietic stem cell",
                "mature nk t cell",
                "mast cell",
                "myeloid cell",
                "non-classical monocyte",
                "platelet",
                "basophil",
                "memory b cell",
                "thymocyte",
                "plasmacytoid dendritic cell",
                "classical monocyte",
                "macrophage",
                "cd4-positive helper t cell",
                "cd8-positive, alpha-beta memory t cell",
                "erythrocyte",
                "immature natural killer cell",
                "b cell",
                "regulatory t cell",
                "innate lymphoid cell",
                "erythroid progenitor cell",
                "dendritic cell",
                "conventional dendritic cell",
                "cd4-positive, alpha-beta t cell",
                "t cell",
                "cd8-positive, alpha-beta t cell",
                "conventional dendritic cell type i",
                "naive thymus-derived cd8-positive, alpha-beta t cell",
                "intermediate monocyte",
                "naive thymus-derived cd4-positive, alpha-beta t cell",
                "neutrophil",
              ],
              line: { color: "black", width: 0.5 },
              pad: 15,
              thickness: 20,
            },
            link: {
              source: [
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                5,
                5,
                5,
                5,
                5,
                8,
                8,
                8,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                13,
                13,
                13,
                13,
                1,
                1,
                1,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
              ],
              target: [
                36,
                31,
                22,
                19,
                15,
                29,
                43,
                26,
                32,
                44,
                30,
                41,
                34,
                47,
                21,
                27,
                17,
                19,
                49,
                24,
                15,
                29,
                25,
                36,
                32,
                44,
                30,
                40,
                39,
                20,
                19,
                49,
                24,
                15,
                36,
                32,
                44,
                31,
                19,
                36,
                44,
                49,
                36,
                26,
                42,
                44,
                30,
                40,
                47,
                31,
                19,
                49,
                24,
                15,
                29,
                16,
                33,
                30,
                45,
                14,
                38,
                47,
                31,
                22,
                21,
                27,
                17,
                48,
                19,
                15,
                37,
                42,
                44,
                34,
                31,
                22,
                21,
                43,
                36,
                22,
                23,
                43,
                36,
                44,
                49,
                16,
                33,
                44,
                30,
                45,
                14,
                34,
                38,
                31,
                21,
                27,
                17,
                48,
                46,
                19,
                49,
                15,
                29,
                25,
                37,
                32,
                44,
                40,
                34,
                35,
                31,
                22,
                21,
                27,
                18,
                17,
                19,
                15,
                28,
                36,
                31,
                22,
                15,
                36,
                34,
                31,
                22,
                19,
                15,
                43,
              ],
              value: [
                251,
                4879,
                992,
                485,
                1146,
                18,
                2628,
                6,
                2722,
                797,
                9146,
                25,
                517,
                176,
                442,
                332,
                690,
                527,
                7,
                129,
                8,
                14,
                202,
                204,
                414,
                573,
                548,
                56,
                292,
                305,
                338,
                47,
                394,
                284,
                345,
                183,
                244,
                330,
                131,
                28,
                42,
                6,
                201,
                688,
                544,
                554,
                1490,
                316,
                252,
                12172,
                108,
                42,
                1006,
                136,
                18,
                1439,
                871,
                85,
                53,
                24,
                370,
                172,
                62,
                25,
                54,
                3326,
                1337,
                1502,
                199,
                261,
                9,
                94,
                269,
                16,
                1345,
                23,
                130,
                330,
                119,
                51,
                85,
                29,
                78,
                94,
                6,
                309,
                822,
                43,
                998,
                33,
                25,
                28,
                27,
                444,
                427,
                2075,
                566,
                238,
                380,
                193,
                70,
                807,
                6,
                11,
                56,
                4256,
                349,
                35,
                9,
                77,
                160,
                11,
                90,
                1853,
                347,
                874,
                105,
                92,
                553,
                18,
                17,
                7,
                6,
                10,
                47,
                1908,
                72,
                95,
                35,
                231,
              ],
            },
          },
        ]}
        layout={{
          width: 800,
          height: 900,
          margin: {
            l: 50,
            r: 50,
            b: 80,
            t: 90,
            pad: 4,
          },
          title: graphData.masterGraph.title,
          annotations: [
            {
              text: graphData.masterGraph.model,
              font: {
                size: 14,
                color: "#444444",
              },
              showarrow: false,
              align: "center",
              x: 0.5,
              y: 1.1,
              xref: "paper",
              yref: "paper",
            },
          ],
          scene: {
            xaxis: {
              title: graphData.masterGraph.xAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            yaxis: {
              title: graphData.masterGraph.yAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            zaxis: {
              title: graphData.masterGraph.zAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
          },
        }}
      />
    );
  }
}

export default MySankeyImmuneComponent;
