import React, { Component } from "react";
import Plot from "react-plotly.js";

const graphData = {
  masterGraph: {
    title: "",
    model: "",
    xAxis: "X-Axis",
    yAxis: "Y-Axis",
    zAxis: "Z-Axis",
  },
};

class MySankeyComponent extends Component {
  render() {
    return (
      <Plot
        data={[
          {
            type: "sankey",
            orientation: "h",
            node: {
              color: [
                "#e7ba52",
                "#6baed6",
                "#843c39",
                "#e7969c",
                "#3182bd",
                "#7b4173",
                "#9c9ede",
                "#969696",
                "#31a354",
                "#d6616b",
                "#cedb9c",
                "#393b79",
                "#8c6d31",
                "#fd8d3c",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#00A1E0",
                "#d41020",
                "#feab49",
                "#fee187",
                "#fc5b2e",
              ],
              label: [
                "Muscle",
                "Small_Intestine",
                "Vasculature",
                "Bladder",
                "Lung",
                "Kidney",
                "Thymus",
                "Trachea",
                "Large_Intestine",
                "Blood",
                "Bone_Marrow",
                "Spleen",
                "Lymph_Node",
                "Pancreas",
                "plasma cell",
                "ciliated cell",
                "monocyte",
                "connective tissue cell",
                "lung microvascular endothelial cell",
                "memory b cell",
                "thymocyte",
                "plasmacytoid dendritic cell",
                "classical monocyte",
                "macrophage",
                "cd4-positive helper t cell",
                "pancreatic delta cell",
                "serous cell of epithelium of bronchus",
                "pancreatic beta cell",
                "mature enterocyte",
                "lung ciliated cell",
                "type ii pneumocyte",
                "t cell",
                "endothelial cell of lymphatic vessel",
                "naive thymus-derived cd8-positive, alpha-beta t cell",
                "naive thymus-derived cd4-positive, alpha-beta t cell",
                "ionocyte",
                "vein endothelial cell",
                "intestinal transient amplifying cell",
                "endothelial cell of artery",
                "mesothelial cell",
                "hematopoietic stem cell",
                "capillary aerocyte",
                "mature nk t cell",
                "mast cell",
                "smooth muscle cell",
                "basal cell",
                "platelet",
                "tendon cell",
                "pancreatic stellate cell",
                "gut endothelial cell",
                "adventitial cell",
                "cd8-positive, alpha-beta memory t cell",
                "secretory cell",
                "alveolar fibroblast",
                "fibroblast",
                "bladder urothelial cell",
                "b cell",
                "regulatory t cell",
                "intestinal crypt stem cell",
                "pericyte cell",
                "endothelial cell",
                "type i pneumocyte",
                "dendritic cell",
                "cd4-positive, alpha-beta t cell",
                "intestinal enteroendocrine cell",
                "pancreatic acinar cell",
                "conventional dendritic cell type i",
                "skeletal muscle satellite stem cell",
                "conventional dendritic cell type ii",
                "fast muscle cell",
                "medullary thymic epithelial cell",
                "naive b cell",
                "duodenum glandular cell",
                "pancreatic pp cell",
                "myeloid cell",
                "goblet cell",
                "intestinal tuft cell",
                "mesenchymal stem cell",
                "myofibroblast cell",
                "erythrocyte",
                "immature natural killer cell",
                "bronchial smooth muscle cell",
                "epithelial cell",
                "paneth cell of epithelium of large intestine",
                "conventional dendritic cell",
                "immature enterocyte",
                "cd8-positive, alpha-beta t cell",
                "cd4-positive, alpha-beta memory t cell",
                "capillary endothelial cell",
                "vascular associated smooth muscle cell",
                "natural killer cell",
                "kidney epithelial cell",
                "non-classical monocyte",
                "paneth cell of epithelium of small intestine",
                "basophil",
                "respiratory goblet cell",
                "pancreatic alpha cell",
                "club cell",
                "endothelial cell of vascular tree",
                "slow muscle cell",
                "innate lymphoid cell",
                "erythroid progenitor cell",
                "pancreatic ductal cell",
                "intermediate monocyte",
                "neutrophil",
                "Stromal",
                "Epithelial",
                "Endothelial",
                "Immune",
              ],
              line: {
                color: "black",
                width: 0.5,
              },
              pad: 15,
              thickness: 20,
            },
            link: {
              source: [
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                3,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                9,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                10,
                5,
                5,
                5,
                5,
                5,
                5,
                5,
                8,
                8,
                8,
                8,
                8,
                8,
                8,
                8,
                8,
                8,
                8,
                8,
                8,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                4,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                12,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                13,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                11,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                6,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                50,
                53,
                56,
                45,
                94,
                55,
                81,
                41,
                88,
                24,
                87,
                63,
                51,
                86,
                15,
                22,
                97,
                17,
                84,
                66,
                68,
                62,
                72,
                60,
                38,
                32,
                98,
                82,
                79,
                101,
                69,
                54,
                75,
                49,
                40,
                85,
                80,
                100,
                103,
                58,
                64,
                37,
                76,
                35,
                91,
                29,
                18,
                23,
                43,
                28,
                42,
                70,
                19,
                77,
                39,
                16,
                74,
                78,
                71,
                34,
                33,
                90,
                104,
                92,
                65,
                96,
                27,
                25,
                102,
                73,
                48,
                83,
                93,
                59,
                14,
                21,
                46,
                57,
                95,
                52,
                26,
                67,
                99,
                44,
                31,
                47,
                20,
                61,
                30,
                89,
                36,
              ],
              target: [
                56,
                55,
                88,
                32,
                54,
                23,
                43,
                78,
                90,
                59,
                14,
                21,
                44,
                31,
                36,
                94,
                24,
                86,
                22,
                84,
                79,
                103,
                42,
                19,
                71,
                90,
                104,
                92,
                14,
                21,
                46,
                56,
                24,
                86,
                22,
                62,
                101,
                40,
                90,
                104,
                92,
                14,
                56,
                24,
                86,
                60,
                91,
                23,
                90,
                56,
                86,
                54,
                75,
                49,
                85,
                58,
                64,
                37,
                76,
                28,
                104,
                83,
                50,
                53,
                56,
                45,
                94,
                81,
                41,
                88,
                63,
                86,
                22,
                97,
                62,
                38,
                32,
                54,
                103,
                35,
                29,
                18,
                23,
                39,
                78,
                90,
                104,
                92,
                59,
                14,
                21,
                95,
                26,
                61,
                30,
                89,
                36,
                87,
                51,
                22,
                66,
                68,
                60,
                100,
                103,
                23,
                43,
                42,
                19,
                71,
                34,
                90,
                14,
                57,
                88,
                63,
                86,
                38,
                32,
                98,
                79,
                69,
                23,
                43,
                42,
                77,
                59,
                67,
                99,
                31,
                47,
                56,
                60,
                43,
                74,
                65,
                96,
                27,
                25,
                102,
                73,
                48,
                31,
                56,
                86,
                72,
                54,
                75,
                49,
                85,
                58,
                64,
                37,
                76,
                28,
                104,
                93,
                87,
                51,
                86,
                22,
                66,
                68,
                60,
                79,
                100,
                23,
                42,
                19,
                71,
                34,
                33,
                90,
                104,
                14,
                21,
                46,
                57,
                88,
                24,
                86,
                62,
                38,
                32,
                79,
                69,
                54,
                80,
                23,
                43,
                42,
                70,
                19,
                39,
                16,
                71,
                90,
                14,
                20,
                89,
                36,
                56,
                45,
                15,
                17,
                60,
                75,
                23,
                43,
                14,
                52,
                56,
                60,
                82,
                79,
                54,
                23,
                43,
                90,
                59,
                14,
                44,
                31,
                105,
                105,
                108,
                106,
                108,
                106,
                105,
                107,
                107,
                108,
                108,
                108,
                108,
                108,
                106,
                108,
                106,
                105,
                108,
                108,
                108,
                108,
                106,
                107,
                107,
                107,
                107,
                106,
                108,
                108,
                105,
                105,
                106,
                107,
                108,
                106,
                108,
                108,
                108,
                106,
                106,
                106,
                106,
                106,
                106,
                106,
                107,
                108,
                108,
                106,
                108,
                106,
                108,
                105,
                106,
                108,
                108,
                105,
                108,
                108,
                108,
                108,
                108,
                108,
                106,
                106,
                106,
                106,
                106,
                106,
                105,
                106,
                106,
                105,
                108,
                108,
                108,
                108,
                106,
                106,
                106,
                105,
                105,
                105,
                108,
                105,
                108,
                106,
                106,
                105,
                107,
              ],
              value: [
                251,
                2874,
                66,
                73,
                4932,
                4879,
                992,
                2020,
                485,
                711,
                1146,
                18,
                227,
                2628,
                266,
                6,
                2722,
                797,
                9146,
                25,
                517,
                176,
                442,
                332,
                690,
                527,
                7,
                129,
                8,
                14,
                202,
                204,
                414,
                573,
                548,
                56,
                292,
                305,
                338,
                47,
                394,
                284,
                345,
                183,
                244,
                95,
                8354,
                330,
                131,
                28,
                42,
                101,
                166,
                23,
                920,
                143,
                36,
                156,
                21,
                545,
                6,
                57,
                350,
                330,
                201,
                2197,
                688,
                83,
                571,
                968,
                544,
                554,
                1490,
                1051,
                316,
                189,
                50,
                13,
                252,
                22,
                605,
                490,
                12172,
                17,
                10,
                108,
                42,
                1006,
                215,
                136,
                18,
                760,
                15,
                213,
                5334,
                81,
                513,
                1439,
                871,
                85,
                53,
                24,
                16,
                370,
                172,
                62,
                25,
                54,
                3326,
                1337,
                1502,
                199,
                261,
                9,
                1502,
                94,
                269,
                98,
                56,
                3111,
                16,
                168,
                1345,
                23,
                130,
                8565,
                1322,
                2896,
                91,
                330,
                181,
                119,
                268,
                51,
                85,
                4816,
                71,
                87,
                9,
                1619,
                71,
                39,
                29,
                78,
                94,
                46,
                25,
                66,
                31,
                371,
                102,
                46,
                100,
                22,
                573,
                6,
                477,
                309,
                822,
                43,
                998,
                33,
                25,
                158,
                28,
                27,
                444,
                427,
                2075,
                566,
                238,
                380,
                193,
                70,
                807,
                6,
                11,
                56,
                988,
                4256,
                349,
                35,
                181,
                15,
                9,
                86,
                673,
                77,
                160,
                11,
                90,
                27,
                1853,
                12,
                347,
                874,
                105,
                92,
                553,
                691,
                663,
                18,
                3913,
                39,
                249,
                33,
                85,
                17,
                7,
                6,
                78,
                10,
                1549,
                26,
                47,
                3030,
                1908,
                72,
                95,
                384,
                35,
                1268,
                231,
                350,
                330,
                1254,
                6110,
                694,
                2874,
                83,
                571,
                3524,
                7575,
                1748,
                638,
                1693,
                2965,
                39,
                12267,
                1051,
                249,
                25,
                86,
                49,
                407,
                46,
                2119,
                468,
                194,
                3111,
                26,
                617,
                292,
                254,
                8774,
                317,
                54,
                305,
                1291,
                77,
                397,
                600,
                245,
                82,
                256,
                43,
                22,
                8354,
                605,
                490,
                21317,
                1181,
                1118,
                1143,
                27,
                7586,
                8565,
                29,
                347,
                85,
                2030,
                3467,
                1740,
                380,
                2181,
                178,
                1529,
                4816,
                71,
                87,
                9,
                1619,
                71,
                39,
                57,
                477,
                2632,
                2775,
                56,
                213,
                65,
                760,
                78,
                15,
                2896,
                91,
                1495,
                3218,
                181,
                553,
                213,
                5334,
                772,
                1442,
              ],
            },
          },
        ]}
        layout={{
          width: 1600,
          height: 1200,
          margin: {
            l: 100,
            r: 50,
            b: 25,
            t: 25,
            pad: 4,
          },
          title: graphData.masterGraph.title,
          annotations: [
            {
              text: graphData.masterGraph.model,
              font: {
                size: 14,
                color: "#444444",
              },
              showarrow: false,
              align: "center",
              x: 0.5,
              y: 1.1,
              xref: "paper",
              yref: "paper",
            },
          ],
          scene: {
            xaxis: {
              title: graphData.masterGraph.xAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            yaxis: {
              title: graphData.masterGraph.yAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
            zaxis: {
              title: graphData.masterGraph.zAxis,
              titlefont: {
                family: "Courier New, monospace",
                size: 12,
                color: "#444444",
              },
            },
          },
        }}
      />
    );
  }
}

export default MySankeyComponent;
